services:
  - type: web
    name: skillpath-backend
    runtime: docker
    dockerfilePath: apps/backend/Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: BASE_URL
        value: https://syncsphere-hiv6.onrender.com
      - key: PORT
        value: 4000
